# frozen_string_literal: true

platform :ios, '11.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

use_frameworks!

def add_flipper_pods!
  version = '~> 0.33.1'
  pod 'FlipperKit', version, configuration: 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', version, configuration: 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', version, configuration: 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', version, configuration: 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', version, configuration: 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    next unless target.name == 'YogaKit'

    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.1'
    end
  end
end

target 'BringgDriverSdkIosExample' do
  # Pods for BringgDriverSdkIosExample
  pod 'FBLazyVector', path: '../node_modules/react-native/Libraries/FBLazyVector'
  pod 'FBReactNativeSpec', path: '../node_modules/react-native/Libraries/FBReactNativeSpec'
  pod 'RCTRequired', path: '../node_modules/react-native/Libraries/RCTRequired'
  pod 'RCTTypeSafety', path: '../node_modules/react-native/Libraries/TypeSafety'
  pod 'React', path: '../node_modules/react-native/'
  pod 'React-Core', path: '../node_modules/react-native/'
  pod 'React-CoreModules', path: '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', path: '../node_modules/react-native/'
  pod 'React-RCTActionSheet', path: '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', path: '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', path: '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', path: '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', path: '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', path: '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', path: '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', path: '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', path: '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', path: '../node_modules/react-native/'

  pod 'React-cxxreact', path: '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', path: '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', path: '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', path: '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/turbomodule/core', path: '../node_modules/react-native/ReactCommon'
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga', modular_headers: true

  pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', podspec: '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # For using Xcode 11.3.1, uncomment the following two lines
  # pod 'BringgDriverSDK', :git => 'https://github.com/bringg/Bringg-iOS-DriverSDK.git', :branch => '1.10.0-xcode-11.3.1'
  # pod 'BringgDriverSDKObjc', :git => 'https://github.com/bringg/Bringg-iOS-DriverSDK.git', :branch => '1.10.0-xcode-11.3.1'

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

#  https://github.com/facebook/flipper/issues/254

$static_framework = %w[
  FlipperKit
  Flipper
  Flipper-Folly
  CocoaAsyncSocket
  ComponentKit
  Flipper-PeerTalk
  Flipper-RSocket
  YogaKit
  CocoaLibEvent
  openssl-ios-bitcode
  boost-for-react-native
]

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  installer.pod_targets.each do |pod|
    next unless $static_framework.include?(pod.name)

    def pod.build_type
      Pod::BuildType.static_library
    end
  end
end
