# frozen_string_literal: true
source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# use_frameworks!

target 'BringgDriverSdkIosExample' do

  pod 'BringgDriverSDKObjc'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  
  #rn_maps_path = '../node_modules/react-native-maps'
  #pod 'react-native-google-maps', :path => rn_maps_path

  # All dependencies of the BringgDriverSDK needs to be built with the 'BUILD_LIBRARY_FOR_DISTRIBUTION' configuration set to 'YES'
  BringgDriverSDKDependencies = [
    'Socket.IO-Client-Swift',
    'Starscream',
    'libPhoneNumber-iOS',
    'GzipSwift',
    'Alamofire',
    'XCGLogger',
    'RealmSwift',
    'ObjcExceptionBridging',
    'Kingfisher',
    'KeychainAccess',
    'DeviceKit'
  ]

  BringgDriverSDKDependencies2 = [
    'Realm',
    'RealmSwift'    
  ]

  RequiredDynamic = [
    'glog',    
    'DoubleConversion',    
  ]

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if BringgDriverSDKDependencies.include? target.name
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
      end
    end
  end
end

#  https://github.com/facebook/flipper/issues/254

# $static_framework = %w[
#   FlipperKit
#   Flipper
#   Flipper-Folly
#   CocoaAsyncSocket
#   ComponentKit
#   Flipper-PeerTalk
#   Flipper-RSocket
#   YogaKit
#   CocoaLibEvent
#   openssl-ios-bitcode
#   boost-for-react-native
#   GoogleMaps
#   Google-Maps-iOS-Utils  
# ]



pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  installer.pod_targets.each do |pod|
    if BringgDriverSDKDependencies.include?(pod.name) 
      def pod.build_type
        Pod::BuildType.dynamic_framework
      end
    end
    if BringgDriverSDKDependencies2.include?(pod.name)
      def pod.build_type
        Pod::BuildType.dynamic_framework
      end
    end
    if RequiredDynamic.include?(pod.name)
      def pod.build_type
        Pod::BuildType.dynamic_framework
      end
    end
  end
end
