# frozen_string_literal: true

platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

use_frameworks!

target 'BringgDriverSdkIosExample' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

#  https://github.com/facebook/flipper/issues/254

$static_framework = %w[
  FlipperKit
  Flipper
  Flipper-Folly
  CocoaAsyncSocket
  ComponentKit
  Flipper-PeerTalk
  Flipper-RSocket
  YogaKit
  CocoaLibEvent
  openssl-ios-bitcode
  boost-for-react-native
]

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  installer.pod_targets.each do |pod|
    next unless $static_framework.include?(pod.name)

    def pod.build_type
      Pod::BuildType.static_library
    end
  end
end
